name: Rspec

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2
    - name: Install dependencies
      run: bundle install
    - name: Checking offenses
      run: bundle exec rubocop

  test-doc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2
    - name: Install dependencies
      run: bundle install
    - name: Testing docs
      run: bundle exec ruby scripts/command_docs.rb check

  test:
    uses: ./.github/workflows/test-suite.yml
    with:
      rubies: '["3.2", "3.3", "3.4", "4.0"]'
